import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { describe, it } from "mocha";
import assert from "node:assert";
import type * as vscode from "vscode";
import type { CtanPackageInfo } from "../../src/cache/ctanApi";
import { PackageCache } from "../../src/cache/packageCache";

// Minimal vscode.ExtensionContext fake
function makeFakeContext(tempStorage: string): vscode.ExtensionContext {
	return {
		globalStorageUri: { fsPath: tempStorage },
		extensionPath: path.resolve(__dirname, "..", "..", ".."),
	} as unknown as vscode.ExtensionContext;
}

// Stub out CTAN queries by pre-populating PackageCache's in-memory resolver
// cache. We just need downloadPackage / ensurePackages to use our pinned
// CTAN responses without any network access.

describe("PackageCache transitive discovery", () => {
	let tempDir: string;

	beforeEach(() => {
		tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "texwasm-pkgcache-"));
	});

	afterEach(() => {
		fs.rmSync(tempDir, { recursive: true, force: true });
	});

	it("ensurePackages discovers transitive \\RequirePackage in downloaded .sty files", async () => {
		const ctx = makeFakeContext(tempDir);
		const cache = new PackageCache(ctx);
		cache.setIncludeExtraBundle(false);

		// Force the preload sets to empty so our packages are never treated as preloaded.
		// (Default behaviour: texlive-basic.js not found in fake extension → empty preload.)

		// Stub queryPackageInfo by pre-populating the private in-memory CTAN
		// query cache (module-level monkey-patching is not possible: esbuild
		// compiles the exports into non-writable getters).
		const fakeInfoAcronym: CtanPackageInfo = {
			name: "acronym",
			ctan: { path: "/macros/latex/contrib/acronym" },
		};
		const fakeInfoSuffix: CtanPackageInfo = {
			name: "suffix",
			ctan: { path: "/macros/latex/contrib/bigfoot" },
		};
		// biome-ignore lint/suspicious/noExplicitAny: private access in tests
		(cache as any).resolvedInfo.set("acronym", fakeInfoAcronym);
		// biome-ignore lint/suspicious/noExplicitAny: private access in tests
		(cache as any).resolvedInfo.set("suffix", fakeInfoSuffix);
		// xstring has no cached files, so pin its CTAN response to null: the
		// real API would otherwise be queried (and the package downloaded) over
		// the network, making this test slow and flaky on CI.
		// biome-ignore lint/suspicious/noExplicitAny: private access in tests
		(cache as any).resolvedInfo.set("xstring", null);

		// Pretend both packages are "downloaded" by writing the on-disk cache.
		const pkgsDir = path.join(tempDir, "packages", "pkgs");
		const acronymDir = path.join(pkgsDir, "acronym");
		fs.mkdirSync(acronymDir, { recursive: true });
		fs.writeFileSync(
			path.join(acronymDir, "acronym.sty"),
			"\\RequirePackage{suffix,xstring}\n",
		);
		fs.writeFileSync(
			path.join(acronymDir, "metadata.json"),
			JSON.stringify({
				name: "acronym",
				version: "1.50",
				downloadedAt: Date.now(),
				files: ["acronym.sty"],
			}),
		);

		const suffixDir = path.join(pkgsDir, "suffix");
		fs.mkdirSync(suffixDir, { recursive: true });
		fs.writeFileSync(
			path.join(suffixDir, "suffix.sty"),
			"\\def\\SuffixPackageLoaded{}\\endinput\n",
		);
		fs.writeFileSync(
			path.join(suffixDir, "metadata.json"),
			JSON.stringify({
				name: "suffix",
				version: "1.5",
				downloadedAt: Date.now(),
				files: ["suffix.sty"],
			}),
		);

		// xstring is intentionally NOT pre-cached to confirm we only include
		// packages that are actually on disk (transitive deps without cache
		// must not produce stray mount entries).

		const sourceContent = "\\usepackage{acronym}\n";
		const entries = await cache.ensurePackages(sourceContent, []);
		const names = entries.map((e) => path.posix.basename(e.targetPath)).sort();
		assert.ok(
			names.includes("acronym.sty"),
			`expected acronym.sty in ${JSON.stringify(names)}`,
		);
		assert.ok(
			names.includes("suffix.sty"),
			`expected suffix.sty in ${JSON.stringify(names)} (transitive discovery)`,
		);
		assert.ok(
			!names.includes("xstring.sty"),
			`expected no xstring.sty in ${JSON.stringify(names)} (not cached)`,
		);
	});

	it("generates the package's own .sty via docstrip when the bundle ships an unrelated .sty (eso-pic)", async () => {
		const ctx = makeFakeContext(tempDir);
		const cache = new PackageCache(ctx);
		cache.setIncludeExtraBundle(false);

		// Simulate a CTAN source-zip download of eso-pic: it ships showframe.sty
		// (an unrelated ready .sty) plus eso-pic.ins/.dtx sources but no
		// eso-pic.sty. The main .sty must be generated by docstrip.
		const pkgDir = path.join(tempDir, "packages", "pkgs", "eso-pic");
		fs.mkdirSync(pkgDir, { recursive: true });
		fs.writeFileSync(
			path.join(pkgDir, "eso-pic.ins"),
			"\\input docstrip.tex\n\\generate{\\file{eso-pic.sty}{\\from{eso-pic.dtx}{package}}}\n\\endinput\n",
		);
		fs.writeFileSync(
			path.join(pkgDir, "eso-pic.dtx"),
			"%<*package>\\ProvidesPackage{eso-pic}[test]\n%</package>\n",
		);
		fs.writeFileSync(
			path.join(pkgDir, "showframe.sty"),
			"\\ProvidesPackage{showframe}\n\\endinput\n",
		);
		fs.writeFileSync(
			path.join(pkgDir, "metadata.json"),
			JSON.stringify({
				name: "eso-pic",
				version: "3.0e",
				downloadedAt: Date.now(),
				files: ["eso-pic.ins", "eso-pic.dtx", "showframe.sty"],
			}),
		);

		// Stub docstrip: the WASM engine runs pdflatex on the .ins; simulate the
		// generated eso-pic.sty.
		cache.setDocstripHandler(async (files) => {
			const ins = files.find((f) => f.path.toLowerCase().endsWith(".ins"));
			assert.ok(ins, "docstrip should receive the package's .ins file");
			return [
				{
					path: "eso-pic.sty",
					content: Buffer.from("\\ProvidesPackage{eso-pic}[generated]\n"),
				},
			];
		});

		const entries = await cache.downloadPackage("eso-pic");
		const esoPic = entries.find(
			(e) => path.posix.basename(e.targetPath) === "eso-pic.sty",
		);
		assert.ok(
			esoPic,
			`expected generated eso-pic.sty in ${JSON.stringify(entries.map((e) => e.targetPath))}`,
		);
		const content = Buffer.from(esoPic.content).toString("utf8");
		assert.match(content, /ProvidesPackage\{eso-pic\}/);
		assert.ok(
			!content.includes("showframe"),
			"eso-pic.sty must not contain showframe content",
		);
	});
});