import { describe, it, before, after } from 'mocha';
import assert from 'node:assert';
import * as vscode from 'vscode';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as pkg from '../../package.json';

const extensionId = pkg.publisher + '.' + pkg.name;
const RECIPE_NAME = 'TeXWASM MakeIndex Test';

describe('TeXWASM MakeIndex', function () {
  this.timeout(600_000);

  let texPath: string;
  let base: string;
  let pdfPath: string;

  before(async function () {
    const workspaceFolder = vscode.workspace.workspaceFolders?.[0];
    if (!workspaceFolder) {
      throw new Error('No workspace folder found');
    }

    const docDir = workspaceFolder.uri.fsPath;
    texPath = path.join(docDir, 'texwasm-makeindex-test.tex');
    base = texPath.replace(/\.tex$/i, '');
    pdfPath = base + '.pdf';

    const texContent = [
      '\\documentclass{article}',
      '\\usepackage{makeidx}',
      '\\makeindex',
      '\\begin{document}',
      'Hello, World!\\index{Hello}',
      'See the back matter.\\index{World!big}',
      '\\printindex',
      '\\end{document}',
    ].join('\n');
    fs.writeFileSync(texPath, texContent, 'utf-8');

    const ext = vscode.extensions.getExtension(extensionId);
    if (!ext) {
      throw new Error(`Extension ${extensionId} not found`);
    }
    if (!ext.isActive) {
      await ext.activate();
    }

    // Configure a recipe that runs makeindex between pdflatex passes
    await vscode.workspace.getConfiguration().update(
      'texwasm.tools',
      [
        { name: 'pdflatex', command: 'pdflatex', args: ['-synctex=1', '-interaction=nonstopmode', '-file-line-error', '%DOC%'] },
        { name: 'makeindex', command: 'makeindex', args: ['%DOCFILE%'] },
      ],
      vscode.ConfigurationTarget.Global,
    );
    await vscode.workspace.getConfiguration().update(
      'texwasm.recipes',
      [{ name: RECIPE_NAME, tools: ['pdflatex', 'makeindex', 'pdflatex', 'pdflatex'] }],
      vscode.ConfigurationTarget.Global,
    );
    await vscode.workspace.getConfiguration().update(
      'texwasm.recipe.default',
      RECIPE_NAME,
      vscode.ConfigurationTarget.Global,
    );

    console.log('[test] Ensuring engine assets are downloaded...');
    await vscode.commands.executeCommand('texwasm.downloadEngine');
    console.log('[test] Engine assets ready.');
  });

  it('generates a PDF with a makeindex-processed index', async function () {
    const doc = await vscode.workspace.openTextDocument(texPath);
    await vscode.window.showTextDocument(doc);

    assert.strictEqual(doc.languageId, 'latex');

    console.log('[test] Running compile command...');
    await vscode.commands.executeCommand('texwasm.compile');

    console.log('[test] Waiting for PDF...');
    let found = false;
    for (let i = 0; i < 120; i++) {
      if (fs.existsSync(pdfPath)) {
        found = true;
        break;
      }
      await new Promise((resolve) => setTimeout(resolve, 1000));
    }

    assert.ok(found, 'PDF file should exist after compilation');

    const stats = fs.statSync(pdfPath);
    assert.ok(stats.size > 0, 'PDF should not be empty');

    // Pass 1 writes raw index entries to the .idx file...
    const idxPath = base + '.idx';
    assert.ok(fs.existsSync(idxPath), '.idx (raw index entries) should be generated');
    const idx = fs.readFileSync(idxPath, 'utf-8');
    assert.ok(idx.includes('\\indexentry{Hello}'), '.idx should contain the "Hello" entry');

    // ...which makeindex processes into the formatted .ind consumed by \printindex
    const indPath = base + '.ind';
    assert.ok(fs.existsSync(indPath), '.ind (formatted index) should be generated by makeindex');
    const ind = fs.readFileSync(indPath, 'utf-8');
    assert.ok(ind.includes('\\begin{theindex}'), '.ind should be a theindex environment');
    assert.ok(/\\item\s+Hello/.test(ind), '.ind should contain the "Hello" entry');
    assert.ok(ind.includes('World'), '.ind should contain the "World" entry');

    const ilgPath = base + '.ilg';
    assert.ok(fs.existsSync(ilgPath), '.ilg (makeindex log) should be generated');
  });

  after(function () {
    for (const ext of ['.tex', '.pdf', '.aux', '.log', '.out', '.synctex.gz', '.idx', '.ind', '.ilg', '.xdv']) {
      const p = base + ext;
      if (fs.existsSync(p)) {
        try {
          fs.unlinkSync(p);
        } catch {
          /* ignore */
        }
      }
    }

    // Reset recipe settings to their defaults
    vscode.workspace
      .getConfiguration()
      .update('texwasm.tools', undefined, vscode.ConfigurationTarget.Global);
    vscode.workspace
      .getConfiguration()
      .update('texwasm.recipes', undefined, vscode.ConfigurationTarget.Global);
    vscode.workspace
      .getConfiguration()
      .update('texwasm.recipe.default', undefined, vscode.ConfigurationTarget.Global);
  });
});
